In [1]:
words = open('names.txt','r').read().splitlines()

In [2]:
import torch

In [3]:
import torch.nn.functional as F

In [6]:
a = [[1,2]]
xs = torch.tensor(a)
xs

tensor([[1, 2]])

In [7]:
xenc = F.one_hot(xs, num_classes=27).float()
xenc

tensor([[[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [75]:
chars = ['.'] + sorted(list(set(''.join(words))))
chars_bi = []
for i in chars:
    for j in chars:
        ch_ = i+j
        chars_bi.append(''.join(ch_))
# chars_bi

In [78]:
stoi_bi = {s:i for i,s in enumerate(chars_bi)}
itos_bi = {i:s for s,i in stoi_bi.items()}
stoi = {s:i for i,s in enumerate(chars)}
itos = {i:s for s,i in stoi.items()}

In [95]:
xs, ys = [], []
for w in words:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2, ch3 in zip(chs, chs[1:], chs[2:]):
        ix1 = stoi_bi[ch1+ch2]
        ix3 = stoi[ch3]
        xs.append(ix1)
        ys.append(ix3)
xs = torch.tensor(xs)
ys = torch.tensor(ys)
num = xs.nelement()
print('number of examples: ',num)

number of examples:  196113


In [96]:
xs

tensor([  5, 148, 364,  ..., 727, 701, 726])

In [97]:
ys

tensor([13, 13,  1,  ..., 26, 24,  0])

In [98]:
g = torch.Generator().manual_seed(2147483647)
xenc = F.one_hot(xs, num_classes=729).float()
xenc.shape

torch.Size([196113, 729])

In [99]:
W = torch.randn((729, 27), generator=g, requires_grad=True)

In [102]:
for k in range(100):
    logits = xenc @ W
    counts = logits.exp()
    probs = counts / counts.sum(1, keepdims=True)
    loss = -probs[torch.arange(num), ys].log().mean()
    print(loss.item())
    
    W.grad = None
    loss.backward()

    W.data += -30 * W.grad

2.912386894226074
2.900967836380005
2.8899002075195312
2.8791685104370117
2.8687584400177
2.858656167984009
2.848849058151245
2.839324712753296
2.8300724029541016
2.8210809230804443
2.8123397827148438
2.8038389682769775
2.7955691814422607
2.7875213623046875
2.7796871662139893
2.7720580101013184
2.7646257877349854
2.757383108139038
2.7503225803375244
2.7434370517730713
2.736720085144043
2.7301642894744873
2.723764419555664
2.7175135612487793
2.71140718460083
2.7054388523101807
2.699604034423828
2.693897247314453
2.6883137226104736
2.682849407196045
2.677499294281006
2.67225980758667
2.6671266555786133
2.6620962619781494
2.657165050506592
2.652329683303833
2.6475865840911865
2.6429331302642822
2.638366222381592
2.633882999420166
2.6294806003570557
2.625156879425049
2.6209092140197754
2.6167349815368652
2.6126320362091064
2.6085989475250244
2.60463285446167
2.6007320880889893
2.5968949794769287
2.5931193828582764
2.5894038677215576
2.5857467651367188
2.582146644592285
2.578601598739624
2.

In [110]:
for i in range(5):
    out = []
    ix = 0

    while True:
        xenc = F.one_hot(torch.tensor([ix]), num_classes=729).float()
        logits = xenc @ W
        counts = logits.exp()
        p = counts / counts.sum(1, keepdims=True)

        ix = torch.multinomial(p, num_samples=1, replacement=True).item()
        out.append(itos[ix])
        if ix % 27 == 0:
            break
    print(''.join(out))

orih.
omavmabloolavmauwzozanadekolelinarelwilanphaadichadelevekedshapmikavnalileviparanhcolbbviufbfh.
phanizejihamqhasplymanaxjky.
ozevidelumauunapanoozapauyh.
ydanapaarashibramayhtbmcjazanarybevingranabsarofalvinibricdbrdenadeisadevnanininivirardcogmalakalwmiagsaxvfaroyusmacalivisarblelolavnalic.
